export type Styles = {
  'actionContainer': string;
  'actions': string;
  'actionsBar': string;
  'adminAllFormsPage': string;
  'adminFormPage': string;
  'adminHeader': string;
  'adminPageContainer': string;
  'adminPageWrapper': string;
  'bannerContainer': string;
  'button': string;
  'card': string;
  'checkboxField': string;
  'content': string;
  'copyUrl': string;
  'dateField': string;
  'deleteButtonContainer': string;
  'draggable': string;
  'field': string;
  'fieldEditor': string;
  'fieldsEditor': string;
  'filePreview': string;
  'filesPicker': string;
  'firstRow': string;
  'form': string;
  'formContainer': string;
  'formDescription': string;
  'formPage': string;
  'fullWidth': string;
  'greenIcon': string;
  'header': string;
  'image': string;
  'imagePicker': string;
  'logo': string;
  'logoSpin': string;
  'modal': string;
  'option': string;
  'readTheDocs': string;
  'redIcon': string;
  'secondRow': string;
  'section': string;
  'sectionEditor': string;
  'subheaderContainer': string;
  'tabItem': string;
  'tabsContainer': string;
  'title': string;
  'titleAndAction': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
